const types = {
  CREATE_USER: "CREATE_USER",
  LOGIN_USER: "LOGIN_USER",
  LOAD_USER: "LOAD_USER",
  FETCH_USERS: "FETCH_USERS",

  ERROR: "ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",

  FETCH_CATEGORIES: "FETCh_CATEGORIES",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  FETCH_CATEGORY_WP: "FETCH_CATEGORY_WP",

  FETCH_FEATUREDS: "FETCH_FEATUREDS",
  CREATE_FEATURED: "CREATE_FEATURED",
  UPDATE_FEATURED: "UPDATE_FEATURED",
  DELETE_FEATURED: "DELETE_FEATURED",

  FETCH_SLIDERS: "FETCH_SLIDERS",
  CREATE_SLIDER: "CREATE_SLIDER",
  UPDATE_SLIDER: "UPDATE_SLIDER",
  DELETE_SLIDER: "DELETE_SLIDER",

  FETCH_REVIEWS: "FETCH_REVIEWS",
  CREATE_REVIEW: "CREATE_REVIEW",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",

  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
};

export default types;
