const types = {
  CREATE_USER: "CREATE_USER",
  LOGIN_USER: "LOGIN_USER",
  LOAD_USER: "LOAD_USER",
  FETCH_USERS: "FETCH_USERS",

  ERROR: "ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",

  FETCH_CATEGORIES: "FETCh_CATEGORIES",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  FETCH_CATEGORY_WP: "FETCH_CATEGORY_WP",
  REMOVE_CATEGORY_MSG: "REMOVE_CATEGORY_MSG",

  FETCH_FEATUREDS: "FETCH_FEATUREDS",
  CREATE_FEATURED: "CREATE_FEATURED",
  UPDATE_FEATURED: "UPDATE_FEATURED",
  DELETE_FEATURED: "DELETE_FEATURED",
  REMOVE_F_C_MSG: "REMOVE_F_C_MSG",

  FETCH_SLIDERS: "FETCH_SLIDERS",
  CREATE_SLIDER: "CREATE_SLIDER",
  UPDATE_SLIDER: "UPDATE_SLIDER",
  DELETE_SLIDER: "DELETE_SLIDER",
  REMOVE_SLIDER_MSG: "REMOVE_SLIDER_MSG",

  FETCH_REVIEWS: "FETCH_REVIEWS",
  CREATE_REVIEW: "CREATE_REVIEW",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",
  REMOVE_REVIEW_MSG: "REMOVE_REVIEW_MSG",

  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_SPECIAL_PRODUCTS: "FETCH_SPECIAL_PRODUCTS",
  FETCH_FEATURED_PRODUCTS: "FETCH_FEATURED_PRODUCTS",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  REMOVE_PRODUCT_MSG: "REMOVE_PRODUCT_MSG",
};

export default types;
